name = "undervalued-estate-scheduler-properstar-uk"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[triggers]
# Staggered: ~ every 15 mins at :12, :27, :42, :57
crons = ["12,27,42,57 * * * *"]
