name = "undervalued-estate-scheduler-primelocation-uk"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[triggers]
# Option B: rotate workers hourly; PrimeLocation at minute 07 on hours 1,5,9,13,17,21 (keeps buy window)
crons = [
  "7 1,5,9,13,17,21 * * *",  # buy-focused rotation
  "22 4 * * *"                # daily rent sweep
]

[observability]
enabled = true
head_sampling_rate = 1.0
