name = "undervalued-estate-scheduler-primelocation-uk"
main = "src/worker.ts"
compatibility_date = "2024-01-01"

[triggers]
# BUY-only windows (minute 07 => doRent=false) at the same frequency as NPC: hours 2,6,10,14,18,22
crons = ["7 2,6,10,14,18,22 * * *"]

[observability]
enabled = true
head_sampling_rate = 1.0
